export const SIGN_UP = 'SIGN_UP';
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const ADDING_ATTENDANT = 'ADDING_ATTENDANT';
export const ADDED_ATTENDANT = 'ADDED_ATTENDANT';
export const ADD_ATTENDANT_ERROR = 'ADDED_ATTENDANT_ERROR';
